module.exports = {
  operation: {
    perform: {
      body: {
        project_name: '{{bundle.inputData.project_name}}',
        pipeline_id: '{{bundle.inputData.selected_pipeline}}',
        target_milestone_id: '{{bundle.inputData.selected_milestone}}',
        start_date: '{{bundle.inputData.start_date}}',
        due_date: '{{bundle.inputData.due_date}}',
        show_forecasted_date: '{{bundle.inputData.show_forecasted_date}}',
        revenue: '{{bundle.inputData.revenue}}',
        is_arr: '{{bundle.inputData.is_arr}}',
        expected_deal_value: '{{bundle.inputData.expected_deal_value}}',
      },
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
        'X-SELECTED-MILESTONE': '{{bundle.inputData.selected_milestone}}',
      },
      method: 'POST',
      removeMissingValuesFrom: { body: true, params: true },
      url: '{{process.env.BASE_URL}}/api/project/info/',
    },
    inputFields: [
      {
        key: 'project_name',
        label: 'Deal Name',
        type: 'string',
        helpText: 'Enter the Deal Name.',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'selected_pipeline',
        label: 'Select Pipeline',
        type: 'string',
        dynamic: 'get_pipeline.id.template_name',
        required: true,
        list: false,
        altersDynamicFields: true,
      },
      {
        key: 'selected_milestone',
        label: 'Select Milestone',
        type: 'string',
        dynamic: 'get_pipeline_stages.id.name',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'start_date',
        label: 'Start Date',
        type: 'datetime',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'due_date',
        label: 'Due Date',
        type: 'datetime',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'show_forecasted_date',
        label: 'Show Forecasted Date',
        type: 'boolean',
        choices: ['true:True', 'false:False'],
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'revenue',
        label: 'Revenue',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'is_arr',
        label: 'Is Arr',
        type: 'string',
        choices: ['true:True', 'false:False'],
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'expected_deal_value',
        label: 'Expected Deal Value',
        type: 'number',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
    ],
    sample: {
      status: 'success',
      project_id: '7455235793758457857',
      account_id: '',
      name: '',
      message: 'Successfully added project',
    },
    outputFields: [
      { key: 'status', label: 'Status' },
      { key: 'project_id', label: 'Project Id' },
      { key: 'account_id', label: 'Account Id' },
      { key: 'name', label: 'Name' },
      { key: 'message', label: 'Message' },
    ],
  },
  display: {
    description: 'Creates a Deal in Projetly.',
    hidden: false,
    label: 'Create Deal',
  },
  key: 'create_deal',
  noun: 'Deal',
};
