module.exports = {
  operation: {
    perform: {
      body: {
        project_name: '{{bundle.inputData.project_name}}',
        project_type: '{{bundle.inputData.project_type}}',
        start_date: '{{bundle.inputData.start_date}}',
        due_date: '{{bundle.inputData.due_date}}',
        is_arr: '{{bundle.inputData.is_arr}}',
        project_fee: '{{bundle.inputData.project_fee}}',
      },
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      method: 'POST',
      url: '{{process.env.BASE_URL}}/api/project/info/',
    },
    inputFields: [
      {
        key: 'project_name',
        label: 'Project Name',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'project_type',
        label: 'Project Type',
        type: 'string',
        choices: {
          onboarding: 'Onboarding',
          service_delivery: 'Service Delivery',
        },
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'start_date',
        label: 'Start Date',
        type: 'datetime',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'due_date',
        label: 'Due Date',
        type: 'datetime',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'is_arr',
        label: 'Is Arr',
        type: 'boolean',
        choices: ['true:True', 'false:False'],
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'project_fee',
        label: 'Project Fee',
        type: 'number',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
    ],
    sample: {
      status: 'success',
      project_id: '7455240550829002753',
      account_id: '',
      name: '',
      message: 'Successfully added project',
    },
    outputFields: [
      { key: 'status', label: 'Status' },
      { key: 'project_id', label: 'Project Id' },
      { key: 'account_id', label: 'Account Id' },
      { key: 'name', label: 'Name' },
      { key: 'message', label: 'Message' },
    ],
  },
  display: {
    description: 'Creates a Project in Projetly.',
    hidden: false,
    label: 'Create Project',
  },
  key: 'create_project',
  noun: 'Project',
};
