const perform = async (z, bundle) => {
  return [bundle.cleanedRequest];
};

const performList = async (z, bundle) => {
  const options = {
    url: `${process.env.MARKETPLACE_URL}/company/`,
    method: "GET",
    headers: { Accept: "application/json" },
    params: {
      limit: 20,
      sort: "-creation_time",
    },
    removeMissingValuesFrom: { params: true },
  };

  const response = await z.request(options);
  return response.json.results || [];
};

module.exports = {
  operation: {
    perform: perform,
    performList: performList,
    sample: {
      id: "7463464076690067457",
      company_id: "7463464076690067457",
      display_id: "COMPANY_0275",
      company_name: "Sample Company",
      domain: "https://sample.com",
      hq_location: {
        country: "India",
        state: "Karnataka",
        city: "Bengaluru",
        address: "sample address",
        zip_code: "456123",
      },
      industry: "sample",
      employee_range: "1-10",
      estimated_arr: "1-5m",
      employees: null,
      description: "Sample Description",
      company_owner: {
        user_id: "7424309824034181121",
        full_name: "Sample Admin",
      },
      company_type: "prospect",
      lead_status: "new",
      operating_regions: ["Africa"],
      customer_segment: "smb",
      icp_fit: "excellent",
      connection_strength: "very_strong",
      connection_source: "founder",
      vendor_being_replaced: null,
      replacement_urgency: "low",
      category: "crm",
      record_source: "ui",
      partner_type: null,
      parent_company: null,
      external_map: null,
      is_draft: false,
      created_by: "7424309824034181121",
      last_updated_by: "7424309824034181121",
      creation_time: "2026-05-22T05:41:40.340054Z",
      last_update_time: "2026-05-22T05:41:40.340054Z",
      lead_status_pipeline_id: "7450876547860271105",
    },
    outputFields: [
      { key: "id", label: "Id" },
      { key: "company_id", label: "Company Id" },
      { key: "display_id", label: "Display Id" },
      { key: "company_name", label: "Company Name" },
      { key: "domain", label: "Domain" },
      { key: "hq_location__country", label: "HQ Country" },
      { key: "hq_location__state", label: "HQ State" },
      { key: "hq_location__city", label: "HQ City" },
      { key: "hq_location__address", label: "HQ Address" },
      { key: "hq_location__zip_code", label: "HQ Zip Code" },
      { key: "industry", label: "Industry" },
      { key: "employee_range", label: "Employee Range" },
      { key: "estimated_arr", label: "Estimated ARR" },
      { key: "employees", label: "Employees" },
      { key: "description", label: "Description" },
      { key: "company_owner__user_id", label: "Company Owner User Id" },
      { key: "company_owner__full_name", label: "Company Owner Full Name" },
      { key: "company_type", label: "Company Type" },
      { key: "lead_status", label: "Lead Status" },
      { key: "operating_regions", label: "Operating Regions" },
      { key: "customer_segment", label: "Customer Segment" },
      { key: "icp_fit", label: "ICP Fit" },
      { key: "connection_strength", label: "Connection Strength" },
      { key: "connection_source", label: "Connection Source" },
      { key: "vendor_being_replaced", label: "Vendor Being Replaced" },
      { key: "replacement_urgency", label: "Replacement Urgency" },
      { key: "category", label: "Category" },
      { key: "record_source", label: "Record Source" },
      { key: "partner_type", label: "Partner Type" },
      { key: "parent_company", label: "Parent Company" },
      { key: "external_map", label: "External Map" },
      { key: "is_draft", label: "Is Draft", type: "boolean" },
      { key: "created_by", label: "Created By" },
      { key: "last_updated_by", label: "Last Updated By" },
      { key: "creation_time", label: "Creation Time", type: "datetime" },
      { key: "last_update_time", label: "Last Update Time", type: "datetime" },
      { key: "lead_status_pipeline_id", label: "Lead Status Pipeline Id" },
    ],
    type: "hook",
    performSubscribe: {
      body: {
        target_url: "{{bundle.targetUrl}}",
        events: "['company_created']",
        app_name: "zapier",
      },
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      method: "POST",
      url: "{{process.env.MARKETPLACE_URL}}/webhook/subscribe/",
    },
    performUnsubscribe: {
      body: { subscriptionId: "{{bundle.subscribeData.id}}" },
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      method: "DELETE",
      url: "{{process.env.MARKETPLACE_URL}}/webhook/unsubscribe/",
    },
  },
  display: {
    description: "Triggers when a new company is created in Projetly.",
    hidden: false,
    label: "New Company Created",
  },
  key: "company_created",
  noun: "Company",
};
