module.exports = {
  operation: {
    perform: { url: "{{process.env.BASE_URL}}/api/company/" },
    sample: {
      company_name: "Sample Company",
      domain: "https://sample_domain.com",
      website: "https://sample_domain.com",
      linkedin_url: null,
      twitter_url: null,
      description: "sample company created for display",
      company_type: "prospect",
      lead_status: { status_key: "new", status_name: "New" },
      lead_status_pipeline_id: "7450876547860271105",
      icp_fit: "excellent",
      operating_regions: ["Asia"],
      connection_strength: "very_strong",
      customer_segment: "smb",
      category: "crm",
      industry: "Technology",
      estimated_arr: "1-5m",
      employee_range: "1-10",
      partner_type: null,
      parent_company: null,
      hq_location: {
        country: "India",
        state: "Karnataka",
        city: "Bengaluru",
        address: null,
        zip_code: "560102",
      },
      company_owner: "7424309824034181121",
    },
    outputFields: [
      { key: "company_name", label: "Company Name" },
      { key: "domain", label: "Domain" },
      { key: "website", label: "Website" },
      { key: "linkedin_url", label: "LinkedIn URL" },
      { key: "twitter_url", label: "Twitter URL" },
      { key: "description", label: "Description" },
      { key: "company_type", label: "Company Type" },
      { key: "lead_status__status_key", label: "Lead status Key" },
      { key: "lead_status__status_name", label: "Lead Status Name" },
      { key: "lead_status_pipeline_id" },
      { key: "icp_fit", label: "ICP Fit" },
      { key: "operating_regions", label: "Operating Regions" },
      { key: "connection_strength", label: "Connection Strength" },
      { key: "connection_source", label: "Connection Source" },
      { key: "customer_segment", label: "Customer Segment" },
      { key: "category", label: "Category" },
      { key: "record_source", label: "Record Source" },
      { key: "industry", label: "Industry" },
      { key: "estimated_arr", label: "Estimated ARR" },
      { key: "employee_range", label: "Employee Range" },
      { key: "partner_type", label: "Partner Type" },
      { key: "parent_company", label: "Parent Company" },
      { key: "hq_location__country", label: "HQ Location Country" },
      { key: "hq_location__state", label: "HQ Location State" },
      { key: "hq_location__city", label: "HQ Location City" },
      { key: "hq_location__address", label: "HQ Location Address" },
      { key: "hq_location__zip_code", label: "HQ Location Zip Code" },
      { key: "company_owner", label: "Company Owner" },
    ],
  },
  display: {
    description: "Triggers when a new company is created.",
    hidden: false,
    label: "New Company Created",
  },
  key: "company_created",
  noun: "Company",
};
