const { makeSubscribe, unsubscribe } = require("../utils/webhook_hooks");

const perform = async (z, bundle) => {
  return [bundle.cleanedRequest];
};

const performList = async (z, bundle) => {
  const options = {
    url: `${process.env.MARKETPLACE_URL}/contact/`,
    method: "GET",
    headers: {
      Accept: "application/json",
      "x-functions-key": "",
    },
    params: { limit: 20, sort: "-creation_time" },
    removeMissingValuesFrom: { params: true },
  };
  const response = await z.request(options);
  return response.json.results || [];
};

module.exports = {
  operation: {
    perform: perform,
    performList: performList,
    sample: {
      id: "7463467538928635905",
      contact_id: "7463467538928635905",
      display_id: "PERSON_0087",
      person_id: "7463467538928635905",
      full_name: "Sample Name",
      first_name: "Sample",
      last_name: "Name",
      primary_email: "jane.doe@example.com",
      secondary_emails: ["jane.alt@example.com"],
      phone: { primary: "+1-555-0100" },
      phones: [
        {
          number: "+1 555 0101",
          e164Number: "+15550101",
          internationalNumber: "+1 555 0101",
          nationalNumber: "555 0101",
          countryCode: "US",
          dialCode: "+1",
        },
      ],
      company: [
        { company_id: "7463464076690067457", company_name: "Sample Company" },
      ],
      company_ids: ["7463464076690067457"],
      contact_owner: { full_name: "Sample Admin" },
      lead_source: "projetly_ui",
      lead_status: "new",
      contact_stage: null,
      location: {
        country: "India",
        state: "Karnataka",
        city: "Bengaluru",
        address: "Sample Address",
        zip_code: "6546532",
      },
      timezone: "Asia/Calcutta",
      language: "en",
      department: "Engineering",
      person_category: { key: "other", name: "UI.pr_other" },
      whatsapp_number: {
        number: "+1 555 0101",
        e164Number: "+15550101",
        internationalNumber: "+1 555 0101",
        nationalNumber: "555 0101",
        countryCode: "US",
        dialCode: "+1",
      },
      preferred_communication_channel: "email",
      influence_level: 1,
      seniority_level: "ic",
      buying_role: "decision_maker",
      signoff_authority: "yes",
      interest_level: 1,
      do_not_contact: "no",
      internal_notes: "Sample Notes",
      reports_to: null,
      linked_user: "7424309824034181121",
      external_map: null,
      responsiveness_score: null,
      engagement_score: null,
      last_activity_date: null,
      average_response_time: null,
      lead_score: null,
      is_draft: false,
      is_system_created: false,
      created_by: "7424309824034181121",
      creation_time: "2026-05-22T05:55:25.801992Z",
      last_update_time: "2026-05-22T05:55:25.801992Z",
      lead_status_pipeline_id: "7450876547713470465",
      login_info: null,
    },
    outputFields: [
      { key: "id", label: "Id" },
      { key: "contact_id", label: "Contact Id" },
      { key: "display_id", label: "Display Id" },
      { key: "person_id", label: "Person Id" },
      { key: "full_name", label: "Full Name" },
      { key: "first_name", label: "First Name" },
      { key: "last_name", label: "Last Name" },
      { key: "primary_email", label: "Primary Email" },
      { key: "secondary_emails", label: "Secondary Emails" },
      { key: "phone__primary", label: "Phone Primary" },
      { key: "phones[]number", label: "Phone Number" },
      { key: "phones[]e164Number", label: "Phone E164 Number" },
      {
        key: "phones[]internationalNumber",
        label: "Phone International Number",
      },
      { key: "phones[]nationalNumber", label: "Phone National Number" },
      { key: "phones[]countryCode", label: "Phone Country Code" },
      { key: "phones[]dialCode", label: "Phone Dial Code" },
      { key: "company[]company_id", label: "Company Id" },
      { key: "company[]company_name", label: "Company Name" },
      { key: "company_ids", label: "Company Ids" },
      { key: "contact_owner__full_name", label: "Contact Owner Full Name" },
      { key: "lead_source", label: "Lead Source" },
      { key: "lead_status", label: "Lead Status" },
      { key: "contact_stage", label: "Contact Stage" },
      { key: "location__country", label: "Country" },
      { key: "location__state", label: "State" },
      { key: "location__city", label: "City" },
      { key: "location__address", label: "Address" },
      { key: "location__zip_code", label: "Zip Code" },
      { key: "timezone", label: "Timezone" },
      { key: "language", label: "Language" },
      { key: "department", label: "Department" },
      { key: "person_category__key", label: "Person Category Key" },
      { key: "person_category__name", label: "Person Category Name" },
      { key: "whatsapp_number__number", label: "WhatsApp Number" },
      { key: "whatsapp_number__e164Number", label: "WhatsApp E164 Number" },
      {
        key: "whatsapp_number__internationalNumber",
        label: "WhatsApp International Number",
      },
      {
        key: "whatsapp_number__nationalNumber",
        label: "WhatsApp National Number",
      },
      { key: "whatsapp_number__countryCode", label: "WhatsApp Country Code" },
      { key: "whatsapp_number__dialCode", label: "WhatsApp Dial Code" },
      {
        key: "preferred_communication_channel",
        label: "Preferred Communication Channel",
      },
      { key: "influence_level", label: "Influence Level", type: "number" },
      { key: "seniority_level", label: "Seniority Level" },
      { key: "buying_role", label: "Buying Role" },
      { key: "signoff_authority", label: "Signoff Authority" },
      { key: "interest_level", label: "Interest Level", type: "number" },
      { key: "do_not_contact", label: "Do Not Contact" },
      { key: "internal_notes", label: "Internal Notes" },
      { key: "reports_to", label: "Reports To" },
      { key: "linked_user", label: "Linked User" },
      { key: "external_map", label: "External Map" },
      { key: "responsiveness_score", label: "Responsiveness Score" },
      { key: "engagement_score", label: "Engagement Score" },
      {
        key: "last_activity_date",
        label: "Last Activity Date",
        type: "datetime",
      },
      { key: "average_response_time", label: "Average Response Time" },
      { key: "lead_score", label: "Lead Score" },
      { key: "is_draft", label: "Is Draft", type: "boolean" },
      { key: "is_system_created", label: "Is System Created", type: "boolean" },
      { key: "created_by", label: "Created By" },
      { key: "creation_time", label: "Creation Time", type: "datetime" },
      { key: "last_update_time", label: "Last Update Time", type: "datetime" },
      { key: "lead_status_pipeline_id", label: "Lead Status Pipeline Id" },
      { key: "login_info", label: "Login Info" },
    ],
    canPaginate: false,
    type: "hook",
    performSubscribe: makeSubscribe("contact_created"),
    performUnsubscribe: unsubscribe,
  },
  display: {
    description: "Triggers when a new contact is created in Projetly.",
    hidden: false,
    label: "New Contact Created",
  },
  key: "contact_created",
  noun: "Contact",
};
