module.exports = {
  operation: {
    perform: {
      headers: { Accept: 'application/json' },
      removeMissingValuesFrom: { body: false, params: false },
      url: '{{process.env.BASE_URL}}/api/contact/',
    },
    sample: {
      first_name: 'Sample',
      last_name: 'Name',
      full_name: 'Sample Name',
      primary_email: 'sample_email@gmail.com',
      primary_phone: '+91 9876543210',
      job_title: 'VP',
      linkedin_url: 'sample_linkedIn_url',
      twitter_url: 'sample_twitter_url',
      location: {
        country: 'India',
        state: 'Karnataka',
        city: 'Bengaluru',
        address: null,
        zip_code: '560102',
      },
      timezone: 'Asia/Calcutta',
      language: 'en',
      person_category: 'customer_contact',
      lead_source: 'projetly_ui',
      lead_status: 'new',
      seniority_level: 'vp',
      department: 'Marketing',
      interest_level: 'high',
      contact_owner_name: 'Owner Name',
    },
    outputFields: [
      { key: 'first_name', label: 'First Name' },
      { key: 'last_name', label: 'Last Name' },
      { key: 'full_name', label: 'Full Name' },
      { key: 'primary_email', label: 'Primary Email' },
      { key: 'primary_phone', label: 'Primary Phone' },
      { key: 'job_title', label: 'Job Title' },
      { key: 'linkedin_url', label: 'LinkedIn URL' },
      { key: 'twitter_url', label: 'Twitter URl' },
      { key: 'location__country', label: 'Country' },
      { key: 'location__state', label: 'State' },
      { key: 'location__city', label: 'City' },
      { key: 'location__address', label: 'Address' },
      { key: 'location__zip_code', label: 'Zip Code' },
      { key: 'timezone', label: 'Timezone' },
      { key: 'language', label: 'Language' },
      { key: 'person_category', label: 'Person Category' },
      { key: 'lead_source', label: 'Lead Source' },
      { key: 'lead_status', label: 'Lead Status' },
      { key: 'seniority_level', label: 'Seniority Level' },
      { key: 'department', label: 'Department' },
      { key: 'interest_level', label: 'Interest Level' },
      { key: 'contact_owner_name' },
    ],
    canPaginate: false,
  },
  display: {
    description: 'Triggers when a new contact is created.',
    hidden: false,
    label: 'New Contact Created',
  },
  key: 'contact_created',
  noun: 'Contact',
};
