const perform = async (z, bundle) => {
  const options = {
    url: `${process.env.BASE_URL}/api/project/info/deals/`,
    method: 'GET',
    headers: {
      Accept: 'application/json',
    },
    params: {},
    removeMissingValuesFrom: {
      body: false,
      params: false,
    },
  };

  return z.request(options).then((response) => {
    const data = response.json;
    const results = data.deals.map((result) => ({
      ...result,
      id: result.project_id,
    }));
    // You can do any parsing you need for results here before returning them
    return results;
  });
};

module.exports = {
  operation: {
    perform: perform,
    sample: {
      project_id: '7454779361359564801',
      project_name: 'sample Deal',
      description: null,
      start_date: '2026-04-27T18:30:00Z',
      due_date: '2026-04-29T18:30:00Z',
      project_score: 5,
      tasks_count: 0,
      milestones_count: 0,
      phase: {},
      tags: [],
      project_manager: {},
      is_arr: false,
      revenue: '$ 0',
      show_forecasted_date: false,
      forecasted_date: null,
      project_fee: null,
      project_owner: {
        user_id: '7424309824034181121',
        full_name: 'Tejash kumar singh',
        profile_image: '',
        email: 'F7NMCRTv7q5Ipu3YUHeOKyQJ5pbQVimu/EfbAf5BlOk=',
        role: 'Organization Admin',
        phone_number: 'aipUCULUoWjhkt99IVXFuQ==',
        is_customer: false,
      },
      health_score: 5,
      account_img: 'assets/images/companies/img-1.png',
      account_name: 'Projetly Marketplace',
      insights: {
        id: 1,
        key: 'on_time',
        text: 'On Time',
        class: 'fa-solid fa-thumbs-up text-success',
      },
      all_milestones: [],
      status: {
        id: 1,
        status_key: 'not_started',
        status_name: 'Not Started',
        color: '#E5BA03',
        icon: 'fa-regular fa-circle',
      },
      stage: {},
      progress: { completed: 0, in_progress: 0, open: 0, total_tasks: 0 },
      region: 'Asia',
      template_id: '7454779361397313537',
      project_users: [],
      project_customers: [
        {
          user_id: '7451938411897688065',
          full_name: 'tejas',
          profile_image: '',
          email: 'hxTAYbV1WNStFI7mU5RS4WejL03YxYDq+qH+4WBlLnQ=',
          role: '',
          is_invite_sent: false,
          invite_sent_at: null,
          phone_number: '',
        },
      ],
      account_id: '7424309865402601473',
      five_milestones: [],
      customer_project_owner: {
        user_id: '7451938411897688065',
        full_name: 'tejas',
        profile_image: '',
        email: 'hxTAYbV1WNStFI7mU5RS4WejL03YxYDq+qH+4WBlLnQ=',
        role: 'Customer',
        phone_number: '',
        is_customer: true,
        is_invite_sent: false,
        invite_sent_at: null,
      },
      external_map: {
        current_milestone_id: '7424309800785154049',
        current_deal_stage: '7424309800785154049',
      },
      follow_up_project_data: null,
      formatted_revenue: '$ 0 ',
      revenue_amount: 0,
      pipeline_id: '7424309800785154049',
      current_milestone_id: '7424309800785154049',
      project_type: 'sales_deal_room',
      project_type_str: 'UI.pr_sales_deal_room',
      position: 1,
      visible_to_all: false,
      status_position: 0,
      expected_deal_value: 464653,
      formatted_deal_value: '$ 464.65 K',
      custom_fields: [],
      id: '7454779361359564801',
    },
    outputFields: [
      { key: 'project_id' },
      { key: 'project_name' },
      { key: 'description' },
      { key: 'start_date' },
      { key: 'due_date' },
      { key: 'project_score' },
      { key: 'tasks_count' },
      { key: 'milestones_count' },
      { key: 'is_arr' },
      { key: 'revenue' },
      { key: 'show_forecasted_date' },
      { key: 'forecasted_date' },
      { key: 'project_fee' },
      { key: 'project_owner__user_id' },
      { key: 'project_owner__full_name' },
      { key: 'project_owner__profile_image' },
      { key: 'project_owner__email' },
      { key: 'project_owner__role' },
      { key: 'project_owner__phone_number' },
      { key: 'project_owner__is_customer' },
      { key: 'health_score' },
      { key: 'account_img' },
      { key: 'account_name' },
      { key: 'insights__id' },
      { key: 'insights__key' },
      { key: 'insights__text' },
      { key: 'insights__class' },
      { key: 'status__id' },
      { key: 'status__status_key' },
      { key: 'status__status_name' },
      { key: 'status__color' },
      { key: 'status__icon' },
      { key: 'progress__completed' },
      { key: 'progress__in_progress' },
      { key: 'progress__open' },
      { key: 'progress__total_tasks' },
      { key: 'region' },
      { key: 'template_id' },
      { key: 'project_customers[]user_id' },
      { key: 'project_customers[]full_name' },
      { key: 'project_customers[]profile_image' },
      { key: 'project_customers[]email' },
      { key: 'project_customers[]role' },
      { key: 'project_customers[]is_invite_sent' },
      { key: 'project_customers[]invite_sent_at' },
      { key: 'project_customers[]phone_number' },
      { key: 'account_id' },
      { key: 'customer_project_owner__user_id' },
      { key: 'customer_project_owner__full_name' },
      { key: 'customer_project_owner__profile_image' },
      { key: 'customer_project_owner__email' },
      { key: 'customer_project_owner__role' },
      { key: 'customer_project_owner__phone_number' },
      { key: 'customer_project_owner__is_customer' },
      { key: 'customer_project_owner__is_invite_sent' },
      { key: 'customer_project_owner__invite_sent_at' },
      { key: 'external_map__current_milestone_id' },
      { key: 'external_map__current_deal_stage' },
      { key: 'follow_up_project_data' },
      { key: 'formatted_revenue' },
      { key: 'revenue_amount' },
      { key: 'pipeline_id' },
      { key: 'current_milestone_id' },
      { key: 'project_type' },
      { key: 'project_type_str' },
      { key: 'position' },
      { key: 'visible_to_all' },
      { key: 'status_position' },
      { key: 'expected_deal_value' },
      { key: 'formatted_deal_value' },
      { key: 'id' },
    ],
  },
  display: {
    description: 'Triggers when a new deal is created.',
    hidden: false,
    label: 'New Deal Created',
  },
  key: 'deal_created',
  noun: 'Deal',
};
