const perform = async (z, bundle) => {
  const options = {
    url: `${process.env.BASE_URL}/api/project/info/`,
    method: 'GET',
    headers: {
      Accept: 'application/json',
    },
    params: {},
    removeMissingValuesFrom: {
      body: false,
      params: false,
    },
  };

  return z.request(options).then((response) => {
    const data = response.json;
    const results = data.results
      .map((result) => ({
        ...result,
        id: result.project_id,
      }))
      .sort((a, b) => new Date(b.start_date) - new Date(a.start_date));

    // You can do any parsing you need for results here before returning them

    return results;
  });
};

module.exports = {
  operation: {
    perform: perform,
    sample: {
      project_id: '7442427864764387329',
      project_name: 'Marketplace Integration',
      description: null,
      start_date: '2026-03-25T04:29:32.165000Z',
      due_date: '2026-06-02T00:00:00Z',
      project_score: 3.4,
      tasks_count: 41,
      milestones_count: 3,
      phase: {},
      tags: [],
      project_manager: {},
      is_arr: false,
      revenue: '$ 0',
      show_forecasted_date: false,
      forecasted_date: null,
      project_fee: null,
      project_owner: {
        user_id: '7424683538143776769',
        full_name: 'Samaresh',
        profile_image: '',
        email: 'I2Z8bo2iXmcvq/oQUxrT4ZE1an/i9ozttMmFmCxOL9g=',
        role: 'Organization Admin',
        phone_number: '',
        is_customer: false,
      },
      health_score: 3.4,
      account_img: 'assets/images/companies/img-1.png',
      account_name: 'Projetly Marketplace',
      insights: {},
      all_milestones: [
        {
          name: 'Week 1',
          color: '#e6ecf5',
          milestone_id: '7442427864802136065',
          status: {
            id: 2,
            status_key: 'in_progress',
            status_name: 'In Progress',
          },
          insight: { id: 4, key: 'running_late', name: 'Running Late' },
          start_date: '',
          end_date: '',
          is_project_due: false,
        },
        {
          name: 'Week 2',
          color: '#f5e8e6',
          milestone_id: '7442427864806330369',
          status: {
            status_id: 1,
            status_key: 'not_started',
            status_name: 'Not Started',
          },
          insight: { id: 1, key: 'on_time', name: 'On Time' },
          start_date: '',
          end_date: '',
        },
        {
          name: 'Week 3',
          color: '#fdf5e8',
          milestone_id: '7442427864810524673',
          status: {
            status_id: 1,
            status_key: 'not_started',
            status_name: 'Not Started',
          },
          insight: { id: 1, key: 'on_time', name: 'On Time' },
          start_date: '',
          end_date: '',
        },
      ],
      status: {
        id: 2,
        status_key: 'in_progress',
        status_name: 'In Progress',
        color: '#50C878',
        icon: 'fa-solid fa-circle-three-quarters',
      },
      stage: {
        name: 'Week 1',
        color: '#e6ecf5',
        milestone_id: '7442427864802136065',
        status: {
          id: 2,
          status_key: 'in_progress',
          status_name: 'In Progress',
        },
        insight: { id: 4, key: 'running_late', name: 'Running Late' },
        start_date: '',
        end_date: '',
        is_project_due: false,
      },
      progress: {
        overdue: 22,
        blocked: 0,
        on_hold: 1,
        completed: 8,
        in_progress: 13,
        open: 0,
        not_started: 19,
        total_tasks: 41,
      },
      region: 'Asia',
      template_id: '7442427864802136065',
      project_users: [
        {
          joining_date: '',
          user_id: '7424683538143776769',
          full_name: 'Samaresh',
          profile_image: '',
          email: 'I2Z8bo2iXmcvq/oQUxrT4ZE1an/i9ozttMmFmCxOL9g=',
          role: 'Organization Admin',
          phone_number: '',
          is_customer: false,
          is_owner: true,
        },
        {
          user_id: '7424309824034181121',
          full_name: 'Tejash kumar singh',
          email: 'F7NMCRTv7q5Ipu3YUHeOKyQJ5pbQVimu/EfbAf5BlOk=',
          profile_image: '',
          role: 'Organization Admin',
          added_date: '2026-03-25T04:32:26.293000',
          joining_date: '',
          phone_number: '',
        },
        {
          user_id: '7442428344802480129',
          full_name: 'Prathamesh',
          profile_image: '',
          email: '93siXlaZM2YjVOSiC9xHo41Qsb/kXEUz65QEON9kWt0=',
          role: 'Admin',
          joining_date: '',
          phone_number: '',
        },
        {
          user_id: '7442430619675529217',
          full_name: 'Rohitha',
          profile_image: '',
          email: 'W4eiuN68JwgNikL4dSfstOCmHPeQMZG5NhgyYL3HfaM=',
          role: 'Admin',
          joining_date: '',
          phone_number: '',
        },
        {
          user_id: '7442432971354673153',
          full_name: 'Sanjeevini',
          profile_image: '',
          email: 'GmMVBE6uLZwUpdsPZUJRZMvsYGAO6zDkrciJmrXypSs=',
          role: 'Admin',
          phone_number: '',
        },
      ],
      project_customers: [],
      account_id: '7424309865402601473',
      five_milestones: [
        {
          name: 'Week 1',
          color: '#e6ecf5',
          milestone_id: '7442427864802136065',
          status: {
            id: 2,
            status_key: 'in_progress',
            status_name: 'In Progress',
          },
          insight: { id: 4, key: 'running_late', name: 'Running Late' },
          start_date: '',
          end_date: '',
          is_project_due: false,
        },
        {
          name: 'Week 2',
          color: '#f5e8e6',
          milestone_id: '7442427864806330369',
          status: {
            status_id: 1,
            status_key: 'not_started',
            status_name: 'Not Started',
          },
          insight: { id: 1, key: 'on_time', name: 'On Time' },
          start_date: '',
          end_date: '',
        },
        {
          name: 'Week 3',
          color: '#fdf5e8',
          milestone_id: '7442427864810524673',
          status: {
            status_id: 1,
            status_key: 'not_started',
            status_name: 'Not Started',
          },
          insight: { id: 1, key: 'on_time', name: 'On Time' },
          start_date: '',
          end_date: '',
        },
      ],
      customer_project_owner: { profile_image: '' },
      external_map: null,
      follow_up_project_data: null,
      formatted_revenue: '$ 0 ',
      revenue_amount: 0,
      pipeline_id: null,
      current_milestone_id: null,
      project_type: 'internal_project',
      project_type_str: 'UI.pr_internal_project',
      position: 1,
      visible_to_all: true,
      status_position: 0,
      expected_deal_value: null,
      formatted_deal_value: '$ 0 ',
      custom_fields: [],
      id: '7442427864764387329',
    },
    outputFields: [
      { key: 'project_id' },
      { key: 'project_name' },
      { key: 'description' },
      { key: 'start_date' },
      { key: 'due_date' },
      { key: 'project_score' },
      { key: 'tasks_count' },
      { key: 'milestones_count' },
      { key: 'is_arr' },
      { key: 'revenue' },
      { key: 'show_forecasted_date' },
      { key: 'forecasted_date' },
      { key: 'project_fee' },
      { key: 'project_owner__user_id' },
      { key: 'project_owner__full_name' },
      { key: 'project_owner__profile_image' },
      { key: 'project_owner__email' },
      { key: 'project_owner__role' },
      { key: 'project_owner__phone_number' },
      { key: 'project_owner__is_customer' },
      { key: 'health_score' },
      { key: 'account_img' },
      { key: 'account_name' },
      { key: 'all_milestones[]name' },
      { key: 'all_milestones[]color' },
      { key: 'all_milestones[]milestone_id' },
      { key: 'all_milestones[]status__id' },
      { key: 'all_milestones[]status__status_key' },
      { key: 'all_milestones[]status__status_name' },
      { key: 'all_milestones[]insight__id' },
      { key: 'all_milestones[]insight__key' },
      { key: 'all_milestones[]insight__name' },
      { key: 'all_milestones[]start_date' },
      { key: 'all_milestones[]end_date' },
      { key: 'all_milestones[]is_project_due' },
      { key: 'all_milestones[]status__status_id' },
      { key: 'status__id' },
      { key: 'status__status_key' },
      { key: 'status__status_name' },
      { key: 'status__color' },
      { key: 'status__icon' },
      { key: 'stage__name' },
      { key: 'stage__color' },
      { key: 'stage__milestone_id' },
      { key: 'stage__status__id' },
      { key: 'stage__status__status_key' },
      { key: 'stage__status__status_name' },
      { key: 'stage__insight__id' },
      { key: 'stage__insight__key' },
      { key: 'stage__insight__name' },
      { key: 'stage__start_date' },
      { key: 'stage__end_date' },
      { key: 'stage__is_project_due' },
      { key: 'progress__overdue' },
      { key: 'progress__blocked' },
      { key: 'progress__on_hold' },
      { key: 'progress__completed' },
      { key: 'progress__in_progress' },
      { key: 'progress__open' },
      { key: 'progress__not_started' },
      { key: 'progress__total_tasks' },
      { key: 'region' },
      { key: 'template_id' },
      { key: 'project_users[]joining_date' },
      { key: 'project_users[]user_id' },
      { key: 'project_users[]full_name' },
      { key: 'project_users[]profile_image' },
      { key: 'project_users[]email' },
      { key: 'project_users[]role' },
      { key: 'project_users[]phone_number' },
      { key: 'project_users[]is_customer' },
      { key: 'project_users[]is_owner' },
      { key: 'project_users[]added_date' },
      { key: 'account_id' },
      { key: 'five_milestones[]name' },
      { key: 'five_milestones[]color' },
      { key: 'five_milestones[]milestone_id' },
      { key: 'five_milestones[]status__id' },
      { key: 'five_milestones[]status__status_key' },
      { key: 'five_milestones[]status__status_name' },
      { key: 'five_milestones[]insight__id' },
      { key: 'five_milestones[]insight__key' },
      { key: 'five_milestones[]insight__name' },
      { key: 'five_milestones[]start_date' },
      { key: 'five_milestones[]end_date' },
      { key: 'five_milestones[]is_project_due' },
      { key: 'five_milestones[]status__status_id' },
      { key: 'customer_project_owner__profile_image' },
      { key: 'external_map' },
      { key: 'follow_up_project_data' },
      { key: 'formatted_revenue' },
      { key: 'revenue_amount' },
      { key: 'pipeline_id' },
      { key: 'current_milestone_id' },
      { key: 'project_type' },
      { key: 'project_type_str' },
      { key: 'position' },
      { key: 'visible_to_all' },
      { key: 'status_position' },
      { key: 'expected_deal_value' },
      { key: 'formatted_deal_value' },
      { key: 'id' },
    ],
  },
  display: {
    description: 'Triggers when a new project is created.',
    hidden: false,
    label: 'New Project Created',
  },
  key: 'project_created',
  noun: 'Project',
};
